### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by fm-davidcraig** [ngageoint/mage-server#57]
I'm sure this is user error but I'm trying to install mage on my own digital ocean server.
After following all the steps I can go to my IP and see the MAGE logo but nothing else. Can any one give me any hints on where to look. 

I do see this in the NPM debug log
17 error Linux 4.15.0-52-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error MAGE@4.5.2 build: `bower install --config.cwd=public --config.interactive=false && grunt build`
22 error Exit status 1
23 error Failed at the MAGE@4.5.2 build script 'bower install --config.cwd=public --config.interactive=false && grunt build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the MAGE package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     bower install --config.cwd=public --config.interactive=false && grunt build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs MAGE
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls MAGE
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by newmanw** [comment]
Looks like you are using a pretty old version. Unfortunately I think bower has reached end of life, as such dependencies are not being pulled/installed. You will need to go to at least 5.1.0, however I would recommend going with the latest release.

**Comment by fm-davidcraig** [comment]
I got this part fixed by doing bower install --allow-root

Now my issue is from the WEB it lets me create an initial user but bombs out at the UID portion. I was reading about MAGE_SESSION_COOKIE_SECURE setting that to false as I’m not using HTTPs at the moment but not sure where that setting is?

Thanks for your help. Also any guidance to switching to SSL I can do lets encrypt was just trying to get basic setup done first.

Thanks,

David

**Comment by fm-davidcraig** [comment]
This is the new error I get right after I hit submit on UID.

2019-08-02T02:58:11.591Z - mongoose: users.findOne({ username: 'quickdeploy' }, { fields: {} }, )
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:694:11)
    at Object.exports.pbkdf2 (crypto.js:682:10)
    at Object.encryptPassword (/opt/mage/utilities/pbkdf2.js:46:12)
    at model.<anonymous> (/opt/mage/models/user.js:89:12)
    at _next (/opt/mage/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/opt/mage/node_modules/hooks-fixed/hooks.js:186:8)
    at /opt/mage/models/user.js:79:5
    at model.Query.<anonymous> (/opt/mage/node_modules/mongoose/lib/model.js:3822:16)
    at /opt/mage/node_modules/kareem/index.js:273:21
    at /opt/mage/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by newmanw** [comment]
Any particular reason you are running 4.5.2?  I suspect you are going to run into compatibility problems if you use the mobile app(s) from the public store.

Regarding the digest error, what version of NodeJS are you using?

**Comment by fm-davidcraig** [comment]
Ok sorry, I did not realize. I was having trouble initially with the curl command and the location. I downloaded wrong version was trying to download latest. Node.js = v8.16.0

I will try install again, should I just delete /opt/mage and start over?

Thanks again I’m not much of a linux guy but trying to set this up for an org I’m volunteer for.

David

**Comment by newmanw** [comment]
No worries, here to help. Yes, I would delete /opt/mage and start fresh with the latest version.

**Comment by fm-davidcraig** [comment]
Ok hopefully last question it seems I have created my admin user and have password but somehow don’t know what the UID is?

Is there a way to find it or reset?

**Comment by newmanw** [comment]
You get to choose your UID when the server is initially setup.  

You can check this in the database by launching the mongo shell in the mage database

`mongo magedb
`

From there query the devices collection

`db.devices.find()
`

You can also check the users collection for your user

`db.users.find()
`

If there are no devices or users I don't think you have made it past initial setup, I suspect that the problem is the MAGE_SESSION_COOKIE_SECURE env variable is not set correctly.  In the same terminal you are running MAGE let check this env variable

`echo $MAGE_SESSION_COOKIE_SECURE`

**Comment by fm-davidcraig** [comment]
Ok so get to the point where I enter a UID and it does not go forward.

I would be happy to give SSH access if anyone would have a look for me?

Looking at the database it created my UID 4050
db.devices.find()

{ "_id" : ObjectId("5d44d36a6cecd152248272db"), "uid" : "4050", "appVersion" : null, "description" : null, "registered" : true, "userAgent" : null, "userId" : null }

But then If I go back to the IP address it says login and does not like my UID?

---------------------------------------------------------------------------\
2019-08-03T00:20:58.030Z - mongoose: users.insert({ lastUpdated: new Date("Sat,                                            03 Aug 2019 00:20:57 GMT"), createdAt: new Date("Sat, 03 Aug 2019 00:20:57 GMT")                                           , username: 'cenadmin', displayName: 'CENADMIN', active: true, roleId: ObjectId(                                           "5d44d2d077fdf611784683a6"), _id: ObjectId("5d44d36977fdf611784683b5"), authenti                                           cation: { type: 'local', password: 'OOC80RRN4NJwt0XFhlhnHGrWCEkXffeLPqXsHII4co/C                                           QzQMhRVNeE06ggRoH5CAyKrAD6is8m3NYafawV/AA4QyrI5nZ5Vw71AktDLZrhSFl94XNz7tCMysNFL8                                           HSqmhH3Os1CHGnRROxc41YeP2SBE8DeG0L/ZvAuVc9WQUfw=::mwgtuETk5DK1xoAeuTwVQCRwGQilw3                                           NLsoWs/osRghWEUjR6+7iFfghKG3clz/uRoraO9PkKqVMMrH3Pjs/ZVayi4gTU+CGuketbBzUt+2nKjw                                           tbARb1DbxnfBnRqFogXdU3otaHVJyUmrXzshRdezNCpjEVfeCrpab7pMsrp3Wz8oKDNwucZgi+GSiCVh                                           AdOUuaqWlU0XIhIlcwF4w7K3KjSAbXkjVADio90lN8eX6F5ft69JXmqX9B+CyfujjDO0Od/p6pYhdRA5                                           fXaiJ6+/dlJHm9/A2NkeJwVn4Z7aHT+ldNU33pvsTdRnsuCBL4mFAbBP+EQnf2XS+OGT4I/A==::256:                                           :12000', security: { numberOfTimesLocked: 0, invalidLoginAttempts: 0 } }, recent                                           EventIds: [], enabled: true, icon: { type: 'none' }, phones: [] }, , )
2019-08-03T00:20:58.035Z - mongoose: roles.find({ _id: { '$in': [ ObjectId("5d44                                           d2d077fdf611784683a6") ] } }, { fields: {} }, )
2019-08-03T00:20:58.040Z - mongoose: devices.findAndModify({ uid: '4050' }, [],                                            { '$set': { description: undefined, userId: undefined, userAgent: undefined, app                                           Version: undefined, registered: true } })
2019-08-03T00:20:58.124Z - mongoose: users.findOne({ username: 'cenadmin' }, { f                                           ields: {} }, )
2019-08-03T00:20:58.126Z - mongoose: roles.find({ _id: { '$in': [ ObjectId("5d44                                           d2d077fdf611784683a6") ] } }, { fields: {} }, )
2019-08-03T00:20:58.242Z - mongoose: users.findOne({ username: 'cenadmin' }, { f                                           ields: {} }, )
2019-08-03T00:20:58.244Z - mongoose: users.update({ _id: ObjectId("5d44d36977fdf                                           611784683b5") }, { '$set': { 'authentication.security': {}, lastUpdated: new Dat                                           e("Sat, 03 Aug 2019 00:20:58 GMT") } }, )
2019-08-03T00:21:47.936Z - mongoose: users.count({}, {}, )
2019-08-03T00:20:57.890Z - mongoose: users.findOne({ _id: ObjectId("5d44d36977fd                                           f611784683b5") }, { fields: {} }, )
2019-08-03T00:20:58.030Z - mongoose: users.insert({ lastUpdated: new Date("Sat,                                            03 Aug 2019 00:20:57 GMT"), createdAt: new Date("Sat, 03 Aug 2019 00:20:57 GMT")                                           , username: 'cenadmin', displayName: 'CENADMIN', active: true, roleId: ObjectId(                                           "5d44d2d077fdf611784683a6"), _id: ObjectId("5d44d36977fdf611784683b5"), authenti                                           cation: { type: 'local', password: 'OOC80RRN4NJwt0XFhlhnHGrWCEkXffeLPqXsHII4co/C                                           QzQMhRVNeE06ggRoH5CAyKrAD6is8m3NYafawV/AA4QyrI5nZ5Vw71AktDLZrhSFl94XNz7tCMysNFL8                                           HSqmhH3Os1CHGnRROxc41YeP2SBE8DeG0L/ZvAuVc9WQUfw=::mwgtuETk5DK1xoAeuTwVQCRwGQilw3                                           NLsoWs/osRghWEUjR6+7iFfghKG3clz/uRoraO9PkKqVMMrH3Pjs/ZVayi4gTU+CGuketbBzUt+2nKjw                                           tbARb1DbxnfBnRqFogXdU3otaHVJyUmrXzshRdezNCpjEVfeCrpab7pMsrp3Wz8oKDNwucZgi+GSiCVh                                           AdOUuaqWlU0XIhIlcwF4w7K3KjSAbXkjVADio90lN8eX6F5ft69JXmqX9B+CyfujjDO0Od/p6pYhdRA5                                           fXaiJ6+/dlJHm9/A2NkeJwVn4Z7aHT+ldNU33pvsTdRnsuCBL4mFAbBP+EQnf2XS+OGT4I/A==::256:                                           :12000', security: { numberOfTimesLocked: 0, invalidLoginAttempts: 0 } }, recent                                           EventIds: [], enabled: true, icon: { type: 'none' }, phones: [] }, , )
2019-08-03T00:20:58.035Z - mongoose: roles.find({ _id: { '$in': [ ObjectId("5d44                                           d2d077fdf611784683a6") ] } }, { fields: {} }, )
2019-08-03T00:20:58.040Z - mongoose: devices.findAndModify({ uid: '4050' }, [],                                            { '$set': { description: undefined, userId: undefined, userAgent: undefined, app                                           Version: undefined, registered: true } })
2019-08-03T00:20:58.124Z - mongoose: users.findOne({ username: 'cenadmin' }, { f                                           ields: {} }, )
2019-08-03T00:20:58.126Z - mongoose: roles.find({ _id: { '$in': [ ObjectId("5d44                                           d2d077fdf611784683a6") ] } }, { fields: {} }, )
2019-08-03T00:20:58.242Z - mongoose: users.findOne({ username: 'cenadmin' }, { f                                           ields: {} }, )
2019-08-03T00:20:58.244Z - mongoose: users.update({ _id: ObjectId("5d44d36977fdf                                           611784683b5") }, { '$set': { 'authentication.security': {}, lastUpdated: new Dat                                           e("Sat, 03 Aug 2019 00:20:58 GMT") } }, )
2019-08-03T00:21:47.936Z - mongoose: users.count({}, {}, )
2019-08-03T00:22:46.802Z - mongoose: users.count({}, {}, )
2019-08-03T00:22:52.648Z - mongoose: tokens.findOne({ token: 'null' }, { fields: {} }, )
2019-08-03T00:22:52.671Z - mongoose: users.count({}, {}, )
2019-08-03T00:22:52.671Z - mongoose: settings.findOne({ type: 'disclaimer' }, { fields: {} }, )
2019-08-03T00:22:52.701Z - mongoose: tokens.findOne({ token: 'null' }, { fields: {} }, )
2019-08-03T00:22:52.754Z - mongoose: tokens.findOne({ token: 'null' }, { fields: {} }, )
2019-08-03T00:22:52.757Z - mongoose: users.count({}, {}, )
2019-08-03T00:22:52.757Z - mongoose: settings.findOne({ type: 'disclaimer' }, { fields: {} }, )
2019-08-03T00:23:10.472Z - mongoose: users.findOne({ username: 'cenadmin' }, { fields: {} }, )
2019-08-03T00:23:10.474Z - mongoose: roles.find({ _id: { '$in': [ ObjectId("5d44d2d077fdf611784683a6") ] } }, { fields: {} }, )
2019-08-03T00:23:10.592Z - mongoose: users.findOne({ username: 'cenadmin' }, { fields: {} }, )
2019-08-03T00:23:10.594Z - mongoose: users.update({ _id: ObjectId("5d44d36977fdf611784683b5") }, { '$set': { 'authentication.security': {}, lastUpdated: new Date("Sat, 03 Aug 2019 00:23:10 GMT") } }, )

**Comment by fm-davidcraig** [comment]
I have done the install several times now and end up at the same place. I cannot seem to get past creating the initial admin user it seem to create it but then does not go past the UID screen. If I re-launch, then I get the normal login as if the setup script is already run. When I look up the UID in the datbase it is there but I get a UID failure when trying to login. I need to get this setup and woudl be happy to even give remote access if anyone would jump and an take a look. Thanks again sorry for being a newbie.

**Comment by danielbarela** [comment]
It sounds like either you are going over https with an incorrect cert or you need to set the MAGE_SESSION_COOKIE_SECURE environment variable to false and go over http

**Comment by fm-davidcraig** [comment]
I’m using a digitalocean server with a public ip for my build I will need to switch to SSL but need to install let’s encrypt etc. I have set MAGE_SESSION_COOKIE_SECURE = False and get same error.

I’m sure it is something simple but I’m running out of ideas.

**Comment by danielbarela** [comment]
Please email me at daniel.barela@gmail.com and I can help you out

**Comment by fm-davidcraig** [comment]
In the end my problem was MAGE_SESSION_COOKIE_SECURE not being set to false the guys here jumped in and helped me and I now have everything working.
________________________________

**Comment by ba5eem** [comment]
Thanks for the guidance, i tried setting to false - and still got the same result. I can see the logs the uid is being saved when created, but once I try to login in again its says: Invalid Device ID

I also tried changing the following:
`cookies: {
    secure: 'false'
  },`

and:
`cookies: {
    secure: false
  },`

Neither methods worked. Maybe its something in my setup: here is my current setup process:
Following software installed on Ubuntu 18.04.2 LTS:
(docker, docker-compose)
`su - root
apt-get install mongodb -y
apt-get install graphicsmagick -y
mkdir /opt/mage
cd /opt/mage
git clone https://github.com/ngageoint/mage-server.git /opt/mage
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
source ~/.bashrc
nvm install 8
npm install
mkdir /var/lib/mage
mongod --config /etc/mongodb.conf
npm run migrate
npm run build
node app.js`

Do you have any other suggestions?

**Comment by restjohn** [comment]
One possibility could be a discrepancy between the time on your browser and your server if you are running the server on a separate machine.  The initial sign-in cookie is valid for only [2 minutes](https://github.com/ngageoint/mage-server/blob/master/express.js#L40).  You can try syncing the clocks of your client and server (time zone should not matter), or you could try increasing the `maxAge` property in the code I linked.  Also, try to sync your server time from an NTP time server.

If you want to recreate your admin user and device you should be able to just delete all the user and device documents from the MongoDB collections, something like
```
use magedb
db.users.remove()
db.devices.remove()
```
Then navigate your browser to your MAGE server (maybe after restarting), and the server should send you through the initial setup again.

**Comment by ba5eem** [comment]
ENV: MAGE_SESSION_COOKIE_SECURE=false

Oh great IDEA! - I didn't think about date issues. Sadly didnt work thou.

**Attempt #1:**
I changed the date to match: still got Invalid ID

**Attempt #2:**
I tried changing maxAge to:   `maxAge: 24 * 60 * 60 * 1000 // 24 hours` - I got this from: https://github.com/expressjs/cookie-session
still got Invalid ID

**Attempt #3:** 
Also tried to sync time from NTP: still got Invalid ID

`db.users.remove({}) & db.devices.remove({})` is very helpful to know thank you so much! that saves me a lot of time, for trying new things :)

I also tried a curl request in the terminal of where the app is running it works for user/password signin - but still receives `Unauthenticated` for UID request. 

Thanks for all your help so far, do you have any other ideas?

**Comment by ba5eem** [comment]
Update: I changed the following:
`app.use(cookieSession({
  secret: secret,
  name: 'mage-session',
  maxAge: 2 * 60 * 1000, // 2 minutes
  **secure: false,**
  sameSite: true
}));`

It now lets me in.

**Comment by newmanw** [comment]
That is  verification that the MAGE_SESSION_COOKIE_SECURE env variable is indeed not _false_.  You need to track down why that is not being set in the environment you are running in.

**Comment by restjohn** [comment]
So if you clear our your `users` and `devices` collections, then load the MAGE root URL in your browser, setup the initial admin user and device, are you logged into your server at that point, or is that when you see the device ID error?  Do you see the error if you log out and try to log back in?  Open your browser's developer tools while you're doing all that and see if you can get any clues from the network request inspector.  Posting that network request log here so we can take a look could be helpful, too.

**Comment by restjohn** [comment]
Whoops, ignore my last message.  I didn't see your update before I posted.

**Comment by restjohn** [comment]
When you start your server, use 
```
> MAGE_SESSION_COOKIE_SECURE=false node app.js
```
or you can add `export MAGE_SESSION_COOKIE_SECURE=false` to the  _.profile_ or _.bashrc_ of the user that runs the MAGE Node process.  Don't forget to `source ~/.profile` as that user before starting the server again, or just exit the terminal session and start a new one.

**Comment by ba5eem** [comment]
Sweet! Thanks - setting the MAGE_SESSION_COOKIE_SECURE env var in .bashrc works - thanks!
