### ISSUE TITLE
Swagger Docs unable to load - console error

### ISSUE THREAD

**Issue by fitzyjoe** [ngageoint/mage-server#86]
In the web client, I clicked on About Mage and then clicked on the link to view the swagger docs.  The docs did not display - the window is blank.  There is an error in the console:

Error: [$injector:unpr] Unknown provider: class Bi{constructor(e){this.el=e}ngAfterViewInit(){Pi()({url:"/api/docs/openapi.yaml",domNode:this.el.nativeElement.querySelector(".swagger-container"),deepLinking:!1,plugins:[Ui,qi]})}}DirectiveProvider <- class Bi{constructor(e){this.el=e}ngAfterViewInit(){Pi()({url:"/api/docs/openapi.yaml",domNode:this.el.nativeElement.querySelector(".swagger-container"),deepLinking:!1,plugins:[Ui,qi]})}}Directive
http://errors.angularjs.org/1.5.11/$injector/unpr?p0=class%20Bi%7Bconstructor(e)%7Bthis.el%3De%7DngAfterViewInit()%7BPi()(%7Burl%3A%22%2Fapi%2Fdocs%2Fopenapi.yaml%22%2CdomNode%3Athis.el.nativeElement.querySelector(%22.swagger-container%22)%2CdeepLinking%3A!1%2Cplugins%3A%5BUi%2Cqi%5D%7D)%7D%7DDirectiveProvider%20%3C-%20class%20Bi%7Bconstructor(e)%7Bthis.el%3De%7DngAfterViewInit()%7BPi()(%7Burl%3A%22%2Fapi%2Fdocs%2Fopenapi.yaml%22%2CdomNode%3Athis.el.nativeElement.querySelector(%22.swagger-container%22)%2CdeepLinking%3A!1%2Cplugins%3A%5BUi%2Cqi%5D%7D)%7D%7DDirective
    at https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:4655925
    at https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:4677684
    at Object.s [as get] (https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:4679193)
    at https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:4677771
    at Object.s [as get] (https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:4679193)
    at https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:1102598
    at e.makeComponentTemplate (https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:1102723)
    at e.getTemplate (https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:1100437)
    at Object.<anonymous> (https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:1111185)
    at https://www-mage.censored/main.0424f4ee4bb0fd8d918d.js:1:4662389 <ui-view class="route-content ng-scope" toggle-feed="$ctrl.toggleFeed">

**Comment by newmanw** [comment]
Fixed here: 10923f7a9b3aaf6d6e6de61145c4e4675438050e, available in next release.
